'use client';
import { useEffect, useId, useRef, useState } from 'react';

type MermaidApi = {
  initialize: (cfg: Record<string, unknown>) => void;
  render: (id: string, chart: string) => Promise<{ svg: string }>;
};

let mermaidPromise: Promise<MermaidApi> | null = null;
let lastInitTheme: 'dark' | 'default' | null = null;

function currentTheme(): 'dark' | 'default' {
  if (typeof document === 'undefined') return 'dark';
  return document.documentElement.dataset.theme === 'light' ? 'default' : 'dark';
}

function loadMermaid(): Promise<MermaidApi> {
  if (!mermaidPromise) {
    mermaidPromise = import('mermaid').then((m) => {
      const mermaid = m.default as MermaidApi;
      const theme = currentTheme();
      mermaid.initialize({
        startOnLoad: false,
        theme,
        securityLevel: 'strict',
        fontFamily: 'Geist, ui-sans-serif, system-ui, -apple-system, sans-serif',
      });
      lastInitTheme = theme;
      return mermaid;
    });
  }
  return mermaidPromise;
}

/** Re-init mermaid if the user has flipped the global theme since last init.
 *  Without this, charts rendered after a theme toggle keep the original theme. */
async function withCurrentTheme(): Promise<MermaidApi> {
  const mermaid = await loadMermaid();
  const theme = currentTheme();
  if (theme !== lastInitTheme) {
    mermaid.initialize({
      startOnLoad: false,
      theme,
      securityLevel: 'strict',
      fontFamily: 'Geist, ui-sans-serif, system-ui, -apple-system, sans-serif',
    });
    lastInitTheme = theme;
  }
  return mermaid;
}

// One MutationObserver shared across every MermaidBlock instance — previously
// each block registered its own, so 10 charts on a page meant 10 observers
// fanning out. We expose a tiny pub/sub over a single observer.
type ThemeListener = () => void;
const _themeListeners = new Set<ThemeListener>();
let _themeObserver: MutationObserver | null = null;
function ensureThemeObserver() {
  if (_themeObserver || typeof MutationObserver === 'undefined' || typeof document === 'undefined') return;
  _themeObserver = new MutationObserver(() => {
    for (const fn of _themeListeners) try { fn(); } catch {}
  });
  _themeObserver.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });
}

export function MermaidBlock({ chart }: { chart: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  // Use React's useId so StrictMode double-mount doesn't reuse the same
  // counter across two effects and confuse mermaid.render's internal id table.
  const id = useId().replace(/[^A-Za-z0-9_-]/g, '_');
  const idRef = useRef(`mmd-${id}`);
  const [error, setError] = useState<string>('');
  const [themeRev, setThemeRev] = useState(0);

  useEffect(() => {
    ensureThemeObserver();
    const fn: ThemeListener = () => setThemeRev((n) => n + 1);
    _themeListeners.add(fn);
    return () => { _themeListeners.delete(fn); };
  }, []);

  useEffect(() => {
    let cancelled = false;
    const trimmed = chart.trim();
    if (!trimmed) {
      setError('');
      if (containerRef.current) containerRef.current.innerHTML = '';
      return;
    }
    withCurrentTheme()
      .then(async (mermaid) => {
        try {
          const { svg } = await mermaid.render(idRef.current, trimmed);
          if (cancelled) return;
          // mermaid runs with `securityLevel: 'strict'` — it sanitizes user
          // input by escaping HTML in node labels. The SVG returned is
          // generated by Mermaid itself, not user-provided markup. We render
          // it via innerHTML because there's no equivalent React API for
          // injecting an SVG document; the trust boundary is Mermaid's
          // sanitizer + our strict securityLevel.
          if (containerRef.current) containerRef.current.innerHTML = svg;
          setError('');
        } catch (e) {
          if (cancelled) return;
          setError(e instanceof Error ? e.message : 'render failed');
        }
      })
      .catch((e: unknown) => {
        if (cancelled) return;
        setError(e instanceof Error ? e.message : 'load failed');
      });
    return () => {
      cancelled = true;
    };
  }, [chart, themeRev]);

  if (error) {
    return (
      <div className="md-mermaid md-mermaid-error">
        <div className="md-mermaid-msg">Mermaid render failed · showing source</div>
        <pre>{chart}</pre>
      </div>
    );
  }

  return <div className="md-mermaid" ref={containerRef} aria-label="Mermaid diagram" />;
}
